"""Init

Revision ID: 5096ddbbc8f3
Revises: 
Create Date: 2026-06-08 05:46:51.660855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5096ddbbc8f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('github_access_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('repo_name', sa.String(length=200), nullable=True),
    sa.Column('repo_owner', sa.String(length=100), nullable=True),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='progress_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('lines_of_code', sa.Integer(), nullable=False),
    sa.Column('complexity_score', sa.Float(), nullable=False),
    sa.Column('maintainability_index', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_lines_of_code', sa.Integer(), nullable=False),
    sa.Column('avg_complexity', sa.Float(), nullable=False),
    sa.Column('max_complexity', sa.Float(), nullable=False),
    sa.Column('technical_debt_hours', sa.Float(), nullable=False),
    sa.Column('code_duplication_pct', sa.Float(), nullable=False),
    sa.Column('test_coverage_pct', sa.Float(), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.CheckConstraint('quality_score >= 0 AND quality_score <= 100', name='quality_range'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('from_file_id', sa.UUID(), nullable=False),
    sa.Column('to_file_id', sa.UUID(), nullable=False),
    sa.Column('dep_type', sa.String(length=50), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='confidence_range'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patterns')
    op.drop_table('dependencies')
    op.drop_table('metrics')
    op.drop_table('insights')
    op.drop_table('files')
    op.drop_table('analyses')
    op.drop_table('users')
    # ### end Alembic commands ###
